version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      - ./secret:/var/www/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql-data: